### ISSUE TITLE
Can we get another release

### ISSUE THREAD

**Issue by warmwaffles** [dimagi/django-cte#20]
I'm running into an issue where `QJoin` has not attribute `join_field` which I see was resolved in 0fc7da78a6d245ac3049adac586ebee47f281221

@millerdev could we get a 1.1.6 release?

**Comment by millerdev** [comment]
@warmwaffles thanks for checking, I also would love to get a new release out the door. Have you had a chance to review the discussion at https://github.com/dimagi/django-cte/issues/17#issuecomment-620172956? That outlines some reasons for why I'm holding off on a release at this time. TLDR I'm concerned that the changes in #18 are too fragile to force on everyone without warning.

I would consider a beta release if it can be done in a way that will only affect people who opt-in to using it (i.e., not be automatically installed by `pip install --upgrade django-cte`). I'll have to research if that's possible.

As a temporary workaround you can install a specific commit like so:

```sh
pip install "git+git://github.com/dimagi/django-cte@ab0cf7e6a0be7a41c6b646377a2e70b1e896c4c1#egg=django-cte"
```

**Comment by warmwaffles** [comment]
@millerdev I'll pull that into my project and see if this helps me. Will report back on Monday mid day.

**Comment by warmwaffles** [comment]
I've had to table the upgrade to 3.0 because there are other issues outstanding with other libraries. I'll revisit this once I get those other issues resolved.

**Comment by warmwaffles** [comment]
@millerdev so I had to clone this project into my main project and found that `QJoin` has issues when trying to join on a non FK field. In my case, I was joining on a text field and was encountering errors.

Here's my "solution", it's not pretty, I don't know why it works, but it does.

```python
    def set_group_by(self, allow_aliases=True):
        """
        Expand the GROUP BY clause required by the query.
        This will usually be the set of all non-aggregate fields in the
        return data. If the database backend supports grouping by the
        primary key, and the query would be equivalent, the optimization
        will be made automatically.
        """
        # Column names from JOINs to check collisions with aliases.
        if allow_aliases:
            column_names = set()
            seen_models = set()
            for join in list(self.alias_map.values())[1:]:  # Skip base table.
                model = join.join_field.related_model
                # ---------------------------------------------------
                # This is shimmed in from the original implementation
                # ---------------------------------------------------
                if not model:
                    continue

                if model not in seen_models:
                    column_names.update(
                        {field.column for field in model._meta.local_concrete_fields}
                    )
                    seen_models.add(model)

        group_by = list(self.select)
        if self.annotation_select:
            for alias, annotation in self.annotation_select.items():
                signature = inspect.signature(annotation.get_group_by_cols)
                if "alias" not in signature.parameters:
                    annotation_class = annotation.__class__
                    msg = (
                        "`alias=None` must be added to the signature of "
                        "%s.%s.get_group_by_cols()."
                    ) % (annotation_class.__module__, annotation_class.__qualname__)
                    warnings.warn(msg, category=RemovedInDjango40Warning)
                    group_by_cols = annotation.get_group_by_cols()
                else:
                    if not allow_aliases or alias in column_names:
                        alias = None
                    group_by_cols = annotation.get_group_by_cols(alias=alias)
                group_by.extend(group_by_cols)
        self.group_by = tuple(group_by)
```

**Comment by millerdev** [comment]
[django-cte v1.2.0](https://pypi.org/project/django-cte/1.2.0/) released! :tada:
