### ISSUE TITLE
Recursive query with 2 parents

### ISSUE THREAD

**Issue by jphilip** [dimagi/django-cte#21]
I was wondering if it is possible to have a recursive query with 2 parent fields with django-cte, i.e., something like this SQL:
```sql
WITH RECURSIVE ped_cte AS (
  SELECT 1 AS n, d.id, d.name, d.father_id, d.mother_id
  FROM dog AS d
  WHERE d.id = 16324  

  UNION ALL

  SELECT n+1, f.id, f.name, f.father_id, f.mother_id
  FROM ped_cte  
  INNER JOIN dog AS f ON ped_cte.father_id = f.id  
  WHERE n < 5

  UNION ALL

  SELECT n+1, m.id, m.name, m.father_id, m.mother_id
  FROM ped_cte  
  INNER JOIN dog AS m ON ped_cte.mother_id = m.id  
  WHERE n < 5  
)
SELECT * FROM ped_cte;
```

Edit by @millerdev to fix code formatting.

**Comment by millerdev** [comment]
@jphilip I don't see why not. Have you tried adding a second `.union(...)` clause in the recursive query expression?

Examples of recursive CTEs can be found in the tests.

https://github.com/dimagi/django-cte/blob/ab0cf7e6a0be7a41c6b646377a2e70b1e896c4c1/tests/test_recursive.py#L34-L52

**Comment by jphilip** [comment]
@millerdev  I did, but for some reason the parents did not get loaded into the object, so I ended up using a bare cursor with sql code similar to what I showed here, but with a materialized path field which in turn allowed me to easily recursively load the data into the object.

**Comment by millerdev** [comment]
@jphilip can you provide a test case that reproduces your issue?

**Comment by millerdev** [comment]
Feel free to re-open if this is still an issue.
