### ISSUE TITLE
Add custom filters on CTE after join

### ISSUE THREAD

**Issue by damianoporta** [dimagi/django-cte#24]
Hello,
i am using **django-cte** with **django-filter**, at the moment i am stuck at adding filters on CTE.

I have two models:
```
class Strategy(models.Model):
    symbol = models.ForeignKey(Symbol, on_delete=models.CASCADE)
    timeframe = models.ForeignKey(Timeframe, on_delete=models.CASCADE)

class Trade(models.Model):
    strategy = models.ForeignKey(Strategy, on_delete=models.CASCADE, related_name='trades')
    profit = models.DecimalField(max_digits=10, decimal_places=5, blank=True, null=True)
    entry_time = models.DateTimeField(blank=True, null=True)   
    balance = models.DecimalField(max_digits=10, decimal_places=5, blank=True, null=True)

```
and this query:
```
cte = With(
    models.Trade.objects.annotate(
        drawdown = Window(
            expression=Max('balance'),
            partition_by=[F('strategy_id')],
            order_by=F('id').asc(),
        ) - F('balance'),              
        gain_op=Case(
            When(profit__gte=0, then=1),
            default=0,
            output_field=IntegerField(),
        ),       
        loss_op=Case(
            When(profit__lt=0, then=1),
            default=0,
            output_field=IntegerField(),
        )                                                                                            
    )
)

qs = (
    cte.join(models.Strategy, id=cte.col.strategy_id)
    .with_cte(cte)            
    .annotate(
        drawdown=Max(cte.col.drawdown),                
        ratio=Sum(cte.col.gain_op) * 100 / (Sum(cte.col.gain_op) + Sum(cte.col.loss_op)),                                
    )                
    .order_by("drawdown")            
)
```
the query works good, i return it as querySet to let django-filter apply its filters.
My problem is that i also need to add a filter on the CTE too, in my case i need a filter like:

**.filter(entry_time__gt=value)**

the problem is that the filters are applied all at once (after the querySet creation), i must add the CTE in the "main" query, otherwise the annotate() will return an error when i call **cte.col.drawdown**
For this reason i hope there is a way to "override" or inject filters on the on the CTE.

What is the correct approach?

**Comment by millerdev** [comment]
The way it's typically done is to add the filter directly the CTE query. In your case it would be
```py
cte = With(
    models.Trade.objects.annotate(
        drawdown = ...
    ).filter(entry_time__gt=value)
)
```

Here's a bit more advanced example of a CTE that references a value from the outer query in a filter

https://github.com/dimagi/django-cte/blob/ab0cf7e6a0be7a41c6b646377a2e70b1e896c4c1/tests/test_cte.py#L332-L341

There are other examples in the tests that may help as well. Please reopen this ticket and post your non-working query if this does not resolve your issue. Preferably, rewrite your query using the [test models](https://github.com/dimagi/django-cte/blob/master/tests/models.py) so I can reproduce the issue.

**Comment by damianoporta** [comment]
@millerdev no, i know that i can add filter on CTE, during the creation of the CTE. I am asking if i can add filters AFTER the:

```
cte.join(models.Strategy, id=cte.col.strategy_id)
    .with_cte(cte) 
```
as i explained above, i create the CTE, then i add the CTE to the join and then pass that querySet to django-fitler that apply its filters. if i create the CTE after the filters i will get an error because **cte.col.drawdown** does not exists if i do not join the CTE.

**Comment by millerdev** [comment]
I don't think this is possible, but it's possible I am still misunderstanding your intent. Can you post a (non-working) example of what you are trying to do?

**Comment by adhamselman** [comment]
Hi @millerdev

I could be wrong but i think this is what @damianoporta is asking for.
In sql, i can create a cte that selects data from a table and applies a row number window function on each subset (as defined by the partition). Then i can select from the cte and filter out only the rows that have row number = 1.

For example lets say i have testresults that are linked to testcases. I can group the results by testcase, order them by execution date and add a row number to each result. Then i can select the most recent testresult for each testcase. I hope the example is clear.

How would we implement this example using django-cte?

**Comment by millerdev** [comment]
@adhamselman please post some example SQL that you want djang-cte to produce.

**Comment by adhamselman** [comment]
@millerdev from https://stackoverflow.com/a/3800572
```sql
WITH summary AS (
    SELECT p.id, 
           p.customer, 
           p.total, 
           ROW_NUMBER() OVER(PARTITION BY p.customer 
                                 ORDER BY p.total DESC) AS rk
      FROM PURCHASES p)
SELECT s.*
  FROM summary s
 WHERE s.rk = 1
```

**Comment by millerdev** [comment]
I don't think the Django ORM can produce a query with a `FROM` clause that does not include a model table, so not sure this is going to be possible currently without doing something hacky like joining to a model/table that has only one row. I think this would require a new feature for django-cte, and possibly django itself. I'll have to think about this some more (and can't prioritize it immediately). Pull requests are welcome!

**Comment by millerdev** [comment]
Hmm, maybe I was looking at the wrong part of the query. I got distracted by the `FROM` clause and never got down to the `WHERE` clause. Could you do what you want by [filtering on an annotation](https://docs.djangoproject.com/en/2.2/topics/db/aggregation/#filtering-on-annotations)? You can reference a CTE column in an annotation like so

https://github.com/dimagi/django-cte/blob/ab0cf7e6a0be7a41c6b646377a2e70b1e896c4c1/tests/test_cte.py#L36

Then should be able to filter on that annotation by adding a filter clause. Here's an adapted version of that test to demonstrate what I mean.
```py
    def test_simple_cte_query(self):
        totals = With(
            Order.objects
            .filter(region__parent="sun")
            .values("region_id")
            .annotate(total=Sum("amount"))
        )
        orders = (
            totals
            .join(Order, region=totals.col.region_id)
            .with_cte(totals)
            .annotate(region_total=totals.col.total)
            .filter(region_total=33)
            .order_by("amount")
        )

        data = [(o.amount, o.region_id, o.region_total) for o in orders]
        self.assertEqual(data, [
            (10, 'mercury', 33),
            (11, 'mercury', 33),
            (12, 'mercury', 33),
        ])
```

**Comment by adhamselman** [comment]
@millerdev 

Brilliant, thank you sir!
