### ISSUE TITLE
CTESubqueryResolver is not in the latest release

### ISSUE THREAD

**Issue by ZachPerkitny** [dimagi/django-cte#25]
Greatly appreciate the work you guys have done on this package,

I noticed support for `OuterRef` in the `Subquery` was added in #19, but it is not available in the latest release on pypi (1.1.5). I would greatly appreciate if you could do another release soon with this functionality.

**Comment by millerdev** [comment]
Hi @ZachPerkitny, I agree! See discussion on https://github.com/dimagi/django-cte/issues/20 and also https://github.com/dimagi/django-cte/issues/17#issuecomment-620172956 for more context and reasons why it has not happened yet. I hope to develop a better solution for Django 3.x at some point. Pull requests are welcome!
