### ISSUE TITLE
How to use in python 2 and django 1.8

### ISSUE THREAD

**Issue by mohammadpooshesh** [dimagi/django-cte#27]
I wanted to use your library but due to the old version of Django (1.8.7) (and python 2.7) I got an error in some functions, is it possible to use this library in older versions of Django?

**Comment by millerdev** [comment]
I'm guessing you are unable to upgrade Django to a newer/supported version. That would be the best option.

I don't think django-cte was ever tested against Django 1.8. [django-cte 0.1.1](https://github.com/dimagi/django-cte/releases/tag/v0.1.1) was tested against Django 1.10. All newer versions have been tested against Django 1.11.

If that doesn't work, you might try forking it and fixing the incompatibilities in your fork? Good luck!
