### ISSUE TITLE
Support Django 4.0

### ISSUE THREAD

**Issue by PeterTillema** [dimagi/django-cte#40]
When using `django-cte` with Django 4.0 I get the following error:
```
...
File ...
    .union(cte.join(Category, parent_id=cte.col.id).values('id'), all=True)
  File "C:\Users\XXX\.virtualenvs\XXX\lib\site-packages\django_cte\cte.py", line 89, in join
    query.join(QJoin(parent, self.name, self.name, on_clause, join_type))
  File "C:\Users\XXX\.virtualenvs\XXX\lib\site-packages\django\db\models\sql\query.py", line 964, in join
    reuse_aliases = [
  File "C:\Users\XXX\.virtualenvs\XXX\lib\site-packages\django\db\models\sql\query.py", line 966, in <listcomp>
    if (reuse is None or a in reuse) and j.equals(join)
  File "C:\Users\XXX\.virtualenvs\XXX\lib\site-packages\django\db\models\sql\datastructures.py", line 185, in equals
    return self.identity == other.identity
AttributeError: 'QJoin' object has no attribute 'identity'
```

It seems the property got added with this commit:
https://github.com/django/django/commit/bbf141bcdc31f1324048af9233583a523ac54c94#diff-7961d220f663d3b5ba4fcb42fa82b34f048de60c655a5c06e369a784e91be1e1

It also throws another error, namely that `CTEQuery.get_compiler() got an unexpected keyword argument 'elide_empty'`. Added in this commit: https://github.com/django/django/commit/f3112fde981052801e0c2121027424496c03efdf.

**Comment by tari** [comment]
Can we also get a release including this fix out on PyPI?

**Comment by millerdev** [comment]
I would love to. Unfortunately `QJoin` was hacked to make it (sort of) work on Django 3.x, and that still has not been fixed. More details can be found in https://github.com/dimagi/django-cte/issues/20.
