### ISSUE TITLE
is there a way to select from a cte without joining it with a model?

### ISSUE THREAD

**Issue by adhamselman** [dimagi/django-cte#48]
i define 3 CTEs. each consecutive cte joins with the previously defined cte. something like this:
with A as (select ... from table), B as (select ... from table join A on (...)), C as (select ... from table join B on (...))

after defining the CTEs, i want to select directly from C without having to join with a model. is that doable?

i tried using raw_cte, but it didnt work and just want to confirm that this is not supported.

Thank you

**Comment by millerdev** [comment]
Yes, you can do that. See the `test_named_ctes` test.

https://github.com/dimagi/django-cte/blob/a3f35fe0689404fbdc1b4bddb308d6dcb179e3f2/tests/test_cte.py#L252-L255

https://github.com/dimagi/django-cte/blob/a3f35fe0689404fbdc1b4bddb308d6dcb179e3f2/tests/test_cte.py#L267-L270

Note that it is not necessary to use recursive CTEs, it's just something being done it that test.

You can run the test to see the generated SQL:
```sh
nosetests tests/test_cte.py:TestCTE.test_named_ctes --nocapture
```

For that one the query is
```sql
WITH RECURSIVE "region_paths" AS (
    SELECT
        "tests_region"."name",
        "tests_region"."name" AS "path"
    FROM
        "tests_region"
    WHERE
        "tests_region"."parent_id" IS NULL
    UNION
    ALL
    SELECT
        "tests_region"."name",
        COALESCE("region_paths"."path",) || COALESCE(
            COALESCE(,) || COALESCE("tests_region"."name",),
        ) AS "path"
    FROM
        "tests_region"
        INNER JOIN "region_paths" ON "tests_region"."parent_id" = ("region_paths"."name")
),
"region_groups" AS (
    SELECT
        "tests_region"."name",
        "region_paths"."path" AS "parent_path",
        "tests_region"."name" AS "parent_name"
    FROM
        "tests_region"
        INNER JOIN "region_paths" ON "tests_region"."name" = ("region_paths"."name")
    UNION
    ALL
    SELECT
        "tests_region"."name",
        "region_groups"."parent_path" AS "parent_path",
        "region_groups"."parent_name" AS "parent_name"
    FROM
        "tests_region"
        INNER JOIN "region_groups" ON "tests_region"."parent_id" = ("region_groups"."name")
),
"region_totals" AS (
    SELECT
        "region_groups"."parent_name" AS "name",
        "region_groups"."parent_path" AS "path",
        COUNT("tests_order"."id") AS "orders_count",
        SUM("tests_order"."amount") AS "region_total"
    FROM
        "tests_order"
        INNER JOIN "region_groups" ON "tests_order"."region_id" = ("region_groups"."name")
    GROUP BY
        "region_groups"."parent_name",
        "region_groups"."parent_path"
)
SELECT
    "tests_region"."name",
    "tests_region"."parent_id",
    "region_totals"."path" AS "path",
    "region_totals"."orders_count" AS "orders_count",
    "region_totals"."region_total" AS "region_total"
FROM
    "tests_region"
    INNER JOIN "region_totals" ON "tests_region"."name" = ("region_totals"."name")
ORDER BY
    "path" ASC
```

**Comment by millerdev** [comment]
Sorry, I just noticed the second part of your question

> after defining the CTEs, i want to select directly from C without having to join with a model. is that doable?

No, that is not possible, but why would you want to do that? Would it work to make the query in C be the final query instead of a CTE?

**Comment by iMakedonsky** [comment]
@millerdev 
> No, that is not possible, but why would you want to do that? Would it work to make the query in C be the final query instead of a CTE?

I've currently run into such a thing.
I want to filter based on window function results and `select * from cte_name;`.

To do that, I could annotate CTE with my window function, then select * from it with a where statement.

**Comment by adhamselman** [comment]
> No, that is not possible, but why would you want to do that? Would it work to make the query in C be the final query instead of a CTE?
I use the CTEs to get the data i need and then want to group/count the data.
I will explore your suggestion by using a raw_cte to count the data as D and then join with a model in the select.
Thank you for your help.

**Comment by artemistomaras** [comment]
Does this example help?

https://github.com/artemistomaras/django-cte-example
