### ISSUE TITLE
Django 4.2 error: each UNION query must have the same number of columns

### ISSUE THREAD

**Issue by adamanthil** [dimagi/django-cte#87]
In Django 4.2, using `UNION` queries with order by and `select_related` causes the above error, as originally referenced in https://github.com/dimagi/django-cte/pull/81#issue-1983991580

We're encountering this now in our production code base, and it is currently preventing an update beyond Django 4.1.

Related: https://github.com/dimagi/django-cte/issues/66

**Comment by millerdev** [comment]
Can you provide an example query that reproduces the issue, preferably using models from the django-cte test suite?

**Comment by adamanthil** [comment]
Let me work on that and get back to you.

**Comment by millerdev** [comment]
This can be reopened if more details are provided.
